In [2]:
import pandas as pd

df = pd.read_csv("raw/SPX/2015/20150102_OData_SPX.csv")
display(df)

,OptionKey,Symbol,ExpirationDate,AskPrice,AskSize,BidPrice,BidSize,LastPrice,PutCall,StrikePrice,Volume,OpenInterest,UnderlyingPrice,DataDate
0,SPX2015-01-17c100.002015-01-02,SPX,2015-01-17,1954.25,1,1951.15,52,972.65,call,100.0,0,5356,2058.19,2015-01-02
1,SPX2015-01-17p100.002015-01-02,SPX,2015-01-17,0.05,60,0.00,0,0.03,put,100.0,0,2,2058.19,2015-01-02
2,SPX2015-01-17c200.002015-01-02,SPX,2015-01-17,1854.20,1,1851.10,52,0.00,call,200.0,0,0,2058.19,2015-01-02
3,SPX2015-01-17p200.002015-01-02,SPX,2015-01-17,0.05,60,0.00,0,0.00,put,200.0,0,0,2058.19,2015-01-02
4,SPX2015-01-17c250.002015-01-02,SPX,2015-01-17,1804.20,1,1801.10,52,0.00,call,250.0,0,0,2058.19,2015-01-02
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6479,SPX2015-12-31p2500.002015-01-02,SPX,2015-12-31,477.50,0,465.50,0,0.00,put,2500.0,0,0,2058.19,2015-01-02
6480,SPX2015-12-31c2600.002015-01-02,SPX,2015-12-31,1.90,0,0.95,0,1.80,call,2600.0,0,1,2058.19,2015-01-02
6481,SPX2015-12-31p2600.002015-01-02,SPX,2015-12-31,574.50,0,562.50,0,0.00,put,2600.0,0,0,2058.19,2015-01-02
6482,SPX2015-12-31c2700.002015-01-02,SPX,2015-12-31,0.90,0,0.10,0,0.00,call,2700.0,0,0,2058.19,2015-01-02
6483,SPX2015-12-31p2700.002015-01-02,SPX,2015-12-31,672.50,0,660.50,0,0.00,put,2700.0,0,0,2058.19,2015-01-02

In [3]:
df2 = pd.read_csv('raw/SPX/2011/20110103_OData_SPX.csv')
display(df2)

,OptionKey,Symbol,ExpirationDate,AskPrice,AskSize,BidPrice,BidSize,LastPrice,PutCall,StrikePrice,Volume,OpenInterest,UnderlyingPrice,DataDate
0,SPX2011-01-22c200.002011-01-03,SPX,2011-01-22,1071.40,31,1066.95,31,521.50,call,200.0,0,250,1271.87,2011-01-03
1,SPX2011-01-22p200.002011-01-03,SPX,2011-01-22,0.05,549,0.00,0,0.03,put,200.0,0,251,1271.87,2011-01-03
2,SPX2011-01-22c300.002011-01-03,SPX,2011-01-22,971.40,31,966.95,31,0.00,call,300.0,0,0,1271.87,2011-01-03
3,SPX2011-01-22p300.002011-01-03,SPX,2011-01-22,0.05,426,0.00,0,0.00,put,300.0,0,0,1271.87,2011-01-03
4,SPX2011-01-22c350.002011-01-03,SPX,2011-01-22,921.40,31,916.95,31,0.00,call,350.0,0,0,1271.87,2011-01-03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1933,SPX2011-12-30p1800.002011-01-03,SPX,2011-12-30,549.60,0,543.60,0,0.00,put,1800.0,0,0,1271.87,2011-01-03
1934,SPX2011-12-30c1900.002011-01-03,SPX,2011-12-30,1.00,0,0.00,0,0.00,call,1900.0,0,0,1271.87,2011-01-03
1935,SPX2011-12-30p1900.002011-01-03,SPX,2011-12-30,649.10,0,643.10,0,0.00,put,1900.0,0,0,1271.87,2011-01-03
1936,SPX2011-12-30c2000.002011-01-03,SPX,2011-12-30,1.00,0,0.00,0,0.00,call,2000.0,0,0,1271.87,2011-01-03
1937,SPX2011-12-30p2000.002011-01-03,SPX,2011-12-30,748.60,0,742.60,0,0.00,put,2000.0,0,0,1271.87,2011-01-03